# Generated by Django 4.0.4 on 2023-07-20 13:29
from django.db import migrations
from django.db.migrations import RunPython


def func(apps, schema_editor):
    from django.core.management import call_command
    call_command("loaddata", "fixture_data.json")


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0001_initial"),
        ("flight", "0001_initial"),
        ('order', '0003_alter_ticket_flight_alter_ticket_order'),
    ]

    operations = [
        RunPython(func, reverse_func)
    ]
